site_name: Ethereum.nix
site_description: Nix packages and NixOS modules for the Ethereum ecosystem
site_url: https://nix-community.github.io/ethereum.nix

repo_url: https://github.com/nix-community/ethereum.nix
edit_uri: edit/main/docs

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  palette:
    # Palette toggle for dark mode
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables

nav:
  - index.md
  - Getting Started:
      - getting-started/installation.md
      - getting-started/running-geth.md
      - getting-started/running-prysm-beacon.md
      - getting-started/backup-and-restore.md
  - Development:
      - development/contributing.md
  - Reference:
      - NixOS Module Options:
          - reference/module-options/erigon.md
          - reference/module-options/geth.md
          - reference/module-options/geth-bootnode.md
          - reference/module-options/nethermind.md
          - reference/module-options/prysm-beacon.md
  - license.md

extra:
  homepage: https://nix-community.github.io/ethereum.nix
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nix-community/ethereum.nix
      name: Ethereum.nix on Github
  generator: false # hide the line "Made with Material for MkDocs"

copyright: Copyright &copy; 2022-2023 Ethereum.nix contributors
